# Generated by Django 3.2.13 on 2022-07-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleApis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('license', models.TextField()),
                ('copyright', models.TextField()),
                ('information', models.TextField()),
                ('author', models.TextField()),
                ('author_email', models.EmailField(max_length=254)),
                ('document_url', models.TextField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
